import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'DNCL2 Lab',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja" className=''>
      <body className="bg-1 dark:text-white">
        {children}
      </body>
    </html >
  )
}
